[package]
name = "public-commitment-fund-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
multiversx-sc-meta = "0.64.1"
multiversx-sc-meta-lib = "0.64.1"
public-commitment-fund = { path = "../" }
