[package]
name = "public-commitment-fund"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.64.1"

[dev-dependencies]
multiversx-sc-scenario = "0.64.1"
